// front_end-frameworks/react/src/App.jsx
import { useState } from "react";
import { Check } from "lucide-react";
import Header from "./components/layout/Header.jsx";
import Hero from "./components/sections/Hero.jsx";
import About from "./components/sections/About.jsx";
import Features from "./components/sections/Features.jsx";
import Insights from "./components/sections/Insights.jsx";
import Contact from "./components/sections/Contact.jsx";
import Footer from "./components/layout/Footer.jsx";

function App() {
  return (
    <>
      <Header />

      <main>
        <Hero />
        <About />
        <Features />
        <Insights />
        <Contact />
      </main>

      <Footer />
    </>
  );
}

export default App;

// front_end-frameworks/vue/src/App.vue
<script setup>
import Header from './components/layout/Header.vue'
import Hero from './components/sections/Hero.vue'
import About from './components/sections/About.vue'
import Features from './components/sections/Features.vue'
import Insights from './components/sections/Insights.vue'
import Contact from './components/sections/Contact.vue'

import Footer from './components/layout/Footer.vue'

</script>

<template>
  <Header />
  <main>
  <Hero />
  <About />
  <Features />
  <Insights />
  <Contact />
  </main>
  <Footer />
</template>
