// front_end-frameworks/svelte/src/App.svelte
<script>
  import Header from "./components/layout/Header.svelte";
  import About from "./components/sections/About.svelte";
  import Features from "./components/sections/Features.svelte";
  import Hero from "./components/sections/Hero.svelte";
  import Footer from "./components/layout/Footer.svelte";
  import Insight from "./components/sections/Insight.svelte";
  import Contact from "./components/sections/Contact.svelte";

</script>

<Header />
<main>
<Hero />
<About />
<Features />
<Insight />
<Contact />
</main>
<Footer />

// front_end-frameworks/vue/src/App.vue
<script setup>
import Header from './components/layout/Header.vue'
import Hero from './components/sections/Hero.vue'
import About from './components/sections/About.vue'
import Features from './components/sections/Features.vue'
import Insights from './components/sections/Insights.vue'
import Contact from './components/sections/Contact.vue'

import Footer from './components/layout/Footer.vue'

</script>

<template>
  <Header />
  <main>
  <Hero />
  <About />
  <Features />
  <Insights />
  <Contact />
  </main>
  <Footer />
</template>
